// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flmayrnyfpvqhdngzbdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsbWF5cm55ZnB2cWhkbmd6YmRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MzcwNzgsImV4cCI6MjA3MzUxMzA3OH0.rtLeOTHt05g0dA13qJ0vnLzrKu_wXOGFeyXAPXVkx5g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});